### ISSUE TITLE
Receive 500 error on plugins homepage when installing

### ISSUE THREAD

**Issue by lstrange** [SondagesPro/LS-arrayTextAdapt#1]
I am having problems accessing the plugins page once I copy the unzipped folder to my plugins folder. I load the plugin into the plugins folder, then I can't access the plugins page. I deleted the plugins folder, recreated it, then reloaded my plugins into the folder. Still same problem. I'm getting a 500 error on page.

Running version 2.06+ Build 160129

Thanks for your help!

**Comment by Shnoulle** [comment]
Hi,

First : did you have this for directory:
./plugin/arrayTextAdapt/arrayTextAdapt.php 

Second : can you activate debug mode:
http://manual.limesurvey.org/Debug_mode temporary on your limesurvey instance

**Comment by Shnoulle** [comment]
The plugin just use init and LS core system at plugin page ...

Then maybe a PHP version issue with LS core.

**Comment by lstrange** [comment]
So, I’m running version 5.3.3 on our test server (which our server admin said they are soon to update the version) but could this version be causing the problem?

**Comment by Shnoulle** [comment]
Sorry, make a potential patch , but need to be tested : https://github.com/SondagesPro/LS-arrayTextAdapt/commit/db371b242afdbe6acad66052a784a2e4d68c18a3
Try with the last version.

And please : report with debug mode at 2 : http://manual.limesurvey.org/Debug_mode and send more information.
An error 500 can be anything.

**Comment by Shnoulle** [comment]
Must test with 1.0.2 release 

Zip updated
