### ISSUE TITLE
Get selected value or selected text for the dropdown?

### ISSUE THREAD

**Issue by catamaican** [SondagesPro/LS-arrayTextAdapt#4]
Is it possible to get the Value or the Text in the expression manager?

I could get the question (.question) but not the selected value or selected text of the dropdown - i've tried with: .shown, .value

Thank you,
Catalin

**Comment by Shnoulle** [comment]
Hi,

1. try without the Plugin : if it don't work : search on limesurvey forum or bug report
2. if it work with LimeSurvey and not with the plugin : put a little lss file (survey export) to test.

Here : limesurvey bug : https://bugs.limesurvey.org/view.php?id=12029 + https://github.com/LimeSurvey/LimeSurvey/commit/e98eec1d22601d327ddcd46c89bd02f77a4f4565

**Comment by catamaican** [comment]
Hi,
I attach a little .lss file
[limesurvey_survey_724773.zip](https://github.com/SondagesPro/LS-arrayTextAdapt/files/754517/limesurvey_survey_724773.zip)

![image](https://cloud.githubusercontent.com/assets/18305539/22646634/023795ae-ec76-11e6-9ffd-f0c8d7b3eb76.png)

**Comment by Shnoulle** [comment]
I confirm : it's a LimeSurvey issue NOT a arrayTextAdapt issue. To control : deactivate the plugin an test.

**Comment by Shnoulle** [comment]
OK, js core broke it ...

**Comment by Shnoulle** [comment]
Fixed in https://github.com/SondagesPro/LS-arrayTextAdapt/commit/7f296bdab132f363731dd78c4ff0fb3234459f47

But : only value are saved : no text. If you need text (.shown) you need

```
{if(Q1_SQ001_SQ001=="A1","Answer for A1")}
{if(Q1_SQ001_SQ001=="A2","Answer for A2")}
{if(Q1_SQ001_SQ001=="A3","Answer for A3")}
```

Next version, i remove https://github.com/SondagesPro/LS-arrayTextAdapt/tree/master/vendor/archon810 and force to use https://github.com/SondagesPro/LS-toolsDomDocument

**Comment by catamaican** [comment]
Thank you. The value is enough - I need a decision based on the answers from dropdowns and the value is much shorter  to use anyway
