### ISSUE TITLE
DropDown values - not working (reopened #4)

### ISSUE THREAD

**Issue by catamaican** [SondagesPro/LS-arrayTextAdapt#5]
Is it possible to get the Value or the Text in the expression manager?

I could get the question (.question) but not the selected value or selected text of the dropdown - i've tried with: .shown, .value
![image](https://cloud.githubusercontent.com/assets/18305539/22646734/865607da-ec76-11e6-857e-69f90edefc81.png)

Thank you,
Catalin
[limesurvey_survey_724773.zip](https://github.com/SondagesPro/LS-arrayTextAdapt/files/754523/limesurvey_survey_724773.zip)

**Comment by Shnoulle** [comment]
Thanks for reporting (and sorry : i really think it work out of the box)

See https://github.com/SondagesPro/LS-arrayTextAdapt/issues/4#issuecomment-277693958
